"""add settings.llm_model

Revision ID: 2cde58a24092
Revises: 1fd90d563f5e
Create Date: 2026-07-12 14:17:19.193626
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cde58a24092'
down_revision: str | None = '1fd90d563f5e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('llm_model', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'llm_model')
    # ### end Alembic commands ###
